on: [push]

jobs:
  docker_context_over_ssh_job: 
    runs-on: ubuntu-latest
    steps:
      - name: Set up docker context over SSH authentication
        uses: amirmarmul/docker-context-ssh-action@v1
        with:
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-username: '${{ secrets.SSH_USERNAME }}'
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          context-name: 'my-docker-context'
      
      - name: Inspect docker context  
        run: |
          docker context ls -q
          cat ~/.ssh/id_rsa
          cat ~/.ssh/known_hosts
